# Generated by Django 5.1.15 on 2026-06-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_push', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=True)),
                ('telegram', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('preferred_time', models.CharField(choices=[('morning', 'утром'), ('day', 'днём'), ('evening', 'вечером'), ('any', 'любое')], default='any', max_length=10)),
                ('dnd_until', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_prefs', to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=32)),
                ('stage', models.CharField(default='push', max_length=10)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('stopped', 'stopped')], default='active', max_length=12)),
                ('critical', models.BooleanField(default=False)),
                ('next_attempt_at', models.DateTimeField()),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('dedup_key', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_jobs', to='accounts.employee')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_jobs', to='surveys.survey')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_9c6a35_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('delivered', 'delivered'), ('opened', 'opened'), ('clicked', 'clicked'), ('failed', 'failed'), ('skipped', 'skipped')], default='sent', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('dedup_key', models.CharField(db_index=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_logs', to='accounts.employee')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_logs', to='surveys.survey')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'created_at'], name='notificatio_employe_0e87bb_idx')],
            },
        ),
    ]
