# Generated by Django 5.1.15 on 2026-06-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_employee_job_title'),
        ('notifications', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationjob',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_jobs', to='surveys.surveyrun'),
        ),
        migrations.AddField(
            model_name='notificationjob',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_jobs', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_logs', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notif_logs', to='surveys.surveyrun'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_logs', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='telegramlink',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to='accounts.employee'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_9c6a35_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['employee', 'created_at'], name='notificatio_employe_0e87bb_idx'),
        ),
    ]
