# Generated by Django 5.1.15 on 2026-06-08 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
        ('surveys', '0002_survey_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('model_used', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='surveys.survey')),
            ],
        ),
    ]
