# Generated by Django 5.1.15 on 2026-06-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insights', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='surveys.surveyrun'),
        ),
        migrations.AddField(
            model_name='insight',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='surveys.survey'),
        ),
        migrations.AddField(
            model_name='surveyreport',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='surveys.surveyrun'),
        ),
        migrations.AddField(
            model_name='surveyreport',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='surveys.survey'),
        ),
    ]
