# Generated by Django 5.1.15 on 2026-06-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_surveyreport'),
        ('surveys', '0002_survey_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='surveyreport',
            name='kpis',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='surveyreport',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='surveys.survey'),
        ),
    ]
